### ISSUE TITLE
Meaning of T and interpretation of Y

### ISSUE THREAD

**Issue by AndreaRusterholz** [DeAngelisA/ISSS23#11]
I don't know if this belongs on gitHub, since it's not actually related to the R code but I'm having trouble understanding the meaning of T and Y in problem set 2. 

1. Treatment T is described in part 1.2 as the presence (1) or absence (0) of health insurance. But in the related question "name treatment" ist mentioned ("create the variable y which reports the observed health for each job applicant, based on her/his name treatment status (T)"). Is this now about names after all as in QSS p. 46f.?

2. The interpretation of Y is also unclear to me. Y is the "indicator of overall health (you can think of it as a standardized summary of multiple health tests)" but how exactly should I think of these tests? Does a high score mean that especially many health risks were found or that the health is especially good?

**Comment by DeAngelisA** [comment]
@AndreaRusterholz : thanks for posting this, it is really useful. In fact, to your point 1: this is a typo, simply replace "job applicant" with "individual". 

On point 2: although both options could work, in this case, a higher value of `y` implies better overall health.

**Comment by AndreaRusterholz** [comment]
Perfect! Thanks for the quick reply.
