### ISSUE TITLE
Show ceteribus paribus in a plot

### ISSUE THREAD

**Issue by gwism** [DeAngelisA/ISSS23#12]
In problem set 2, there is an exercise where we have to show that age and education are ceteribus paribus.  Online I found the function ceteris_paribus 

ceteris_paribus(
  explainer,
  observations,
  y = NULL,
  variable_splits = NULL,
  variables = NULL,
  grid_points = 101
)

I am not sure if this is correct, and if so, what would be the explainer and what would be the observations?

**Comment by DeAngelisA** [comment]
@gwism: hi Gian, thanks! Could you please post the package and some context? 
In any case: no external functions are needed to solve PS2.

**Comment by gwism** [comment]
The library is also called library (ceterisParibus).But I think this is not relevant for PS2

**Comment by marcograf1** [comment]
I'm having difficulty in understanding the task: 
_build plots to show that the ceteris paribus assumption holds true for age and education_.  

Can somebody rephrase what we are supposed to do? Thanks!

**Comment by DeAngelisA** [comment]
@marcograf1: are treated and non-treated similar? Or could there be some selection bias?
