### ISSUE TITLE
PS#2 Download format

### ISSUE THREAD

**Issue by andreagomezp** [DeAngelisA/ISSS23#13]
Hi!

I'm trying to download my Rmarkdown file in PDF but every time I try to knit I get the following error and only the graphics are saved as PDF.

<img width="748" alt="Captura de pantalla 2021-11-10 a las 16 42 24" src="https://user-images.githubusercontent.com/91679024/141147258-4634b039-4a39-4e61-b8b6-a721ad478cf9.png">

Does it happen to someone else or know how to fix it?

**Comment by DeAngelisA** [comment]
@andreagomezp: we mentioned this in class: to compile in pdf you need to install latex (this is mentioned [in the book as well](https://r4ds.had.co.nz/r-markdown-formats.html#documents)). You can click on the arrow next to "Knit" and choose to compile as HTML.
