### ISSUE TITLE
PS3 1.2

### ISSUE THREAD

**Issue by LauraMariaGrawehr** [DeAngelisA/ISSS23#15]
Hello everybody :)
I'm really struggling with 1.2. 
I know that the formula for the expected value is: E(x)= xi* P(xi) 
So I thought maybe: 500 (winning sum) * 0.5  + 5 (loosing sum) * 0.5 but then we know from exercise 1.1 that winning (which means having five consecutive heads in a row) has a smaller probability than loosing. But I don't know where to put those probabilities and also I'm very confused how/ where to use these brackets []. 
Can anyone help me?

**Comment by DeAngelisA** [comment]
Hi @LauraMariaGrawehr: you can approximate the average expected amount of win/loss... just using the `10,000` simulations from point 2.1! :)
