### ISSUE TITLE
2.2.3

### ISSUE THREAD

**Issue by SimonSchmitter** [DeAngelisA/ISSS23#16]
Hi Guys,

So I really AM struggling with the "for loop" including the creation of these 5000 dataframes. I managed to set the two empty vectors.
I don't get how I can include the creation of these df's with the caluculation of the mean / model. Do I have to set both in these brackets: {  }  and how am I supposed to combine these? 

To receive the mean of the any variable, like the reservation price (var = res_price) I have to relate to a specific value, like if I store my df to x (**x <- tibble(...)**), I can code:

```r
res_mean[i]  <- mean(x$res_price)
```

, but of course there are 5000 df, not just one. How can I refer to different df's in this code?

**Comment by DeAngelisA** [comment]
@SimonSchmitter : It sounds like you are really getting your hands dirty... very good, this is the best way to learn things for real!
Coming to your question: 
1. you got it perfectly right! So, everything that happens in the brackets (body of the `for` loop) is exactly like outside, just the iterator (`i` in my slides) will be replaced with the elements in the vector. For instance, in: `for (i in 1:nsims) {}`, you would have `i=1` in the first iteration, `i = 2` in the second... `i=nsims` in the last one). 
2. To change the `df`... maybe you can just place it inside the loop? ;)

**Comment by SimonSchmitter** [comment]
Thanks for the help!. I think I managed it. I thought You could like only put one line of code in the {} brackets, but as I have seen I can put just any code. :)
