### ISSUE TITLE
Final assignment: missing values

### ISSUE THREAD

**Issue by LauraMariaGrawehr** [DeAngelisA/ISSS23#18]
Hello everyone :)

When I use  is.na("variable") to look if there are missing values, R always returns FALSE although I can see missing values when I look at the data. 
Have you encountered the same?

**Comment by LinhRamirez** [comment]
You can try this one:

```{r}
expl_vec1 <- c(4, 8, 12, NA, 99, - 20, NA) # Create your own example vector with NA's   is.na(expl_vec1) # The is.na() function returns a logical vector. The vector is TRUE in case                  # of a missing value and FALSE in case of an observed value which(is.na(expl_vec1)) # The which() function returns the positions with missing values in your vector.                         # In our case there are NA's at positions 4 & 7 ### [1] 4 7
```

Thsi tipp was from this page: https://statisticsglobe.com/r-find-missing-values/
Not sure if it helps? :)

**Comment by LauraMariaGrawehr** [comment]
@LinhRamirez 
Thank you for this input! Yes, with this command R shows me the missing values :)
Still I find it weird that it didn't work with is.na()

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr : when you type `is.na("variable")`, R understands that you are trying to check whether the word `"variable"` is missing, which is not. It is like typing `is.na("cat")`. 

What you want to do is typing `is.na(dat$variable)`, replacing `dat` and `variable` with your own. Also check out `table(is.na(dat$variable))`.

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA 
Yes, sorry I meant ` is.na(data_climat$educ)`
Thank you, yes this `table(is.na(dat$variable))`  is very useful to get an overview!

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr : is the issue solved?

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA Yes :)
