### ISSUE TITLE
Final assignment: vectors

### ISSUE THREAD

**Issue by LauraMariaGrawehr** [DeAngelisA/ISSS23#19]
![Github](https://user-images.githubusercontent.com/91691466/146353833-915abe70-9d11-4d87-932d-7cd72579d3e9.png)

Hello everyone :)

I wanted to transform my variable "education_level "such that the numbers from the data set correspond to different levels of education. But R returns to me that this vector has to be logical and not double. This makes no sense to me, because the variable is constituted by different education levels from 1 to 7 and not just TRUE or FALSE.  
Does someone know what might be the problem?

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr : reading your code is very hard. try to reproduce the error with simpler lines. 
Here I wrote some code that seems to work just fine: 

```r
library(tidyverse)
tibble(educ = sample(x = 1:6, size = 20, replace = TRUE)) %>% 
  mutate(
    educ =   case_when(
      educ <= 3 ~ "low", 
      educ > 2 ~ "high"
    )
  )

# A tibble: 20 x 1
   educ 
   <chr>
 1 low  
 2 low  
 3 low  
 4 high 
 5 low  
 6 high 
 7 high 
 8 high 
 9 high 
10 low  
11 low  
12 low  
13 high 
14 high 
15 high 
16 low  
17 high 
18 high 
19 low  
20 low  
```

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA Thank you for your example. Does this mean that I'm only allowed to create two categories with the variable education_level , "high" and "low",  because it should be a logical vector?

**Comment by LauraMariaGrawehr** [comment]
Dear Marco, 
Thank you some much for sharing this. It was extremely helpful because I could solve my problem with this approach :)

**Comment by DeAngelisA** [comment]
> ansform my variable "education_level

No, you can have more than two categories. Note that the `educ` variable in my example code is of type `chr`. 

Someting to check: are you sure that the `eisced` variable in your data is numeric? It could be the problem if it's not.

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA Yes, `eisced` is an integer variable. I don't know why it didn't work with `case_when` but Marco's approach worked! So I'm happy :)
