### ISSUE TITLE
Final assignment: Contingency tables

### ISSUE THREAD

**Issue by andreagomezp** [DeAngelisA/ISSS23#21]
Hello everyone, 

I am working in my final assignment and I am stuck in a problem. 

To summarize, I have three variables: 
1) Age -> It is a factor with 3 values: "18-30 years", "31-65 years", "66 or more years"
2) Year of the survey -> Numeric variable (2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018)
3) Interest in politics -> With 4 values: 1 (Not at all interested), 2(Hardly interested), 3(Quite interested), 4(Very interested)

I want to see the average interest by age over the years. It would be like making a contingency table between the three variables. After much trying, I have only managed to reach the solution with the Stata program, which gives me the output of what I want to achieve:
table cat_age year, c(mean interest) format(%9.2f) center
<img width="582" alt="Captura de pantalla 2021-12-20 a las 12 51 39" src="https://user-images.githubusercontent.com/91679024/146763154-d5347077-6b9d-42ac-89ce-813e945df9a9.png">

Does anyone know how to reach the same solution with R?

**Comment by DeAngelisA** [comment]
@andreagomezp: you need nothing else than the usual `dplyr` verbs: 

```r
library(tidyverse)
tibble(
  age = sample(1:3, 1000, replace = TRUE), 
  year = sample(seq(from = 2002, to = 2018, by = 2), 1000, replace = TRUE), 
  polint = sample(1:4, 1000, replace = TRUE)
) %>% 
  group_by(age, year) %>% 
  summarize(avg_polint = mean(polint), 
            n = n(), 
            .groups = "drop")

# A tibble: 27 x 3
     age  year avg_polint
   <int> <dbl>      <dbl>
 1     1  2002       2.21
 2     1  2004       2.65
 3     1  2006       3   
 4     1  2008       2.78
 5     1  2010       2.3 
 6     1  2012       2.55
 7     1  2014       2.17
 8     1  2016       2.37
 9     1  2018       2.48
10     2  2002       2.84
# ... with 17 more rows
```

You can use this as data to create a plot, or make it flat as yours by adding a [pivot_wider()](https://tidyr.tidyverse.org/articles/pivot.html) call to the previous code chunk: 

```r
%>% pivot_wider(names_from = "year", values_from = "avg_polint", names_prefix = "year-")

# A tibble: 3 x 10
    age `year-2002` `year-2004` `year-2006` `year-2008`
  <int>       <dbl>       <dbl>       <dbl>       <dbl>
1     1        2.67        2.48        3           2.39
2     2        2.72        2.70        2.67        2.43
3     3        2.41        2.87        2.47        2.31
# ... with 5 more variables: year-2010 <dbl>, year-2012 <dbl>,
#   year-2014 <dbl>, year-2016 <dbl>, year-2018 <dbl>
```

You can get a nicely formatted table in Rmarkdown with [able()](https://bookdown.org/yihui/rmarkdown-cookbook/kable.html).

**Comment by andreagomezp** [comment]
Thank you very much.

But when I try to knit it with this code:
`tibble <- tibble (catage = ESS$cat_age, year= ESS$year, interest = ESS$interest) %>%
  group_by(cat_age, year) %>% 
  summarize(avg_interest = mean(interest), .groups = "drop") %>%
  pivot_wider(names_from = "year", values_from = "avg_interest", names_prefix = "year-")
knitr::kable(tibble, col.names = gsub("[.]", " ", names(tibble)))`

 it gives me this error:
<img width="887" alt="Captura de pantalla 2021-12-23 a las 11 27 37" src="https://user-images.githubusercontent.com/91679024/147227301-c4aee6fa-eee6-4ac0-a9d3-b7983f4b69d4.png">

**Comment by DeAngelisA** [comment]
@andreagomezp : do you start a new line when creating the table (knitr::kable)?

**Comment by andreagomezp** [comment]
I attached the code and the error:
<img width="901" alt="Captura de pantalla 2021-12-23 a las 12 10 34" src="https://user-images.githubusercontent.com/91679024/147232373-3ee44ea7-b027-4637-b564-8a8da5c7584c.png">

<img width="948" alt="Captura de pantalla 2021-12-23 a las 12 10 38" src="https://user-images.githubusercontent.com/91679024/147232386-5eb8499c-4786-4505-8025-1c2d983073ab.png">
