### ISSUE TITLE
Final assignment: Plot

### ISSUE THREAD

**Issue by LauraMariaGrawehr** [DeAngelisA/ISSS23#22]
![image](https://user-images.githubusercontent.com/91691466/146901696-39451c83-036b-4640-bcbf-75edca0cd88c.png)
Hello everybody :)
I'm a bit unsure about the gap in my plot, do I interpret this correctly that none of the respondents can be assigned with a materialist value of ~ 3.55 -3.7?

**Comment by DeAngelisA** [comment]
@LauraMariaGrawehr: it is not possible to answer this question without looking at the data and the code. Nobody knows this index better than you! :)

**Comment by LauraMariaGrawehr** [comment]
@DeAngelisA Thank you, after looking at the data again I think I interpreted it correctly.
