### ISSUE TITLE
Question: downloading data using "raw" button

### ISSUE THREAD

**Issue by ltrell** [DeAngelisA/ISSS23#27]
@DeAngelisA I'm sorry, I already have problems with the first excercise in the R script. We have to import data from the website using "Raw" button. I know, that the button exists on Github, but how do I do it using data from Kaggle? I have already downloaded the dataset from the website and I have no problems importing it from my computer, but I don't understand how to import it from Kaggle website without the html code.

I used the code:
pokemon <- read.csv('https://www.kaggle.com/datasets/abcsds/pokemon/download')

But if I want to see my table in RStudio, it's just html code. Thanks!

**Comment by AngrodAlcarin** [comment]
@ltrell On Kaggle, you need to download the dataset via your browser and put into your working directory. Your working directory is where R operates at the moment. In the exercise, 1.B, we already are recommended to change the working directory to a folder you can keep track of using setwd(). Then, after putting the csv there (after unzipping), just use 
pokemon<-read.csv("Pokemon.csv")

**Comment by DeAngelisA** [comment]
Thanks for the question!

As you say: the Raw button allows downloading raw data from GitHub. 
For instance, here is the dataset about "bad drivers": [link](https://github.com/fivethirtyeight/data/blob/master/bad-drivers/bad-drivers.csv) and the data can be downloaded clicking on the button "Raw" that is in the top right of the page. 

On Kaggle, you can just click on "Download" to get the data. 
I checked and I could get your .csv data (the Pokemons?!). The file works, here is a plot of the defense & attack points of Pokemons by type: 
![image](https://github.com/DeAngelisA/ISSS23/assets/9892396/e2516d67-734a-461c-99c6-5551f2b417d8)

Hope this helps!

**Comment by ltrell** [comment]
Thanks for your answers! I was sure that I need to import the dataset from the website, not from my computer. Sorry for trouble!
