### ISSUE TITLE
Perusall - How can I highlight text?

### ISSUE THREAD

**Issue by nigi1992** [DeAngelisA/ISSS23#34]
I like to highlight certain keywords and phrases while reading difficult texts, as it helps me memorize and focus on certain aspects. However, in the Perusal Software highlighting a word or a sentence, will instead activate the annotation function. Going through all the settings I did not find a solution. 
Simply downloading the file is not possible, as 1) Perusal doesn't let me. And 2) I don't want to read the text twice. Highlighting the text on a separate document would mean I would have to read the same text parallel.

**Comment by DeAngelisA** [comment]
Dear @nigi1992: your observation about the annotation feature being activated when trying to highlight is a valid point. Perusall is primarily designed for collaborative annotation, which has pros (e.g., the class collaborates to better understand the text and you can ask questions if something is unclear) and cons (e.g., the direct relationship with the text is lost). These are my reactions: 

1. you should able to download all the texts, I just checked: 
![image](https://github.com/DeAngelisA/ISSS23/assets/9892396/5ba5d2b9-5585-4e2d-b2d8-b0e13e343063)

So, in theory, you could underline on your pdf file (I don't recommend that: see point 3); 

2. You can take screenshots of important sections if you want to keep something important; 

3. you can switch from passive underlining, to active notes where you identify the key concepts and then write your own definition.

By taking notes you will be learning actively, elaborating the text you are reading. Here is a [more detailed explanation](https://www.learningscientists.org/elaboration) of this concept. These active elaboration techniques (summarizing, self-questioning, making analogies, making applications, exemplify) are far better than underlining for memory and retention. Of course, underlining is not bad and can be effective when mixed with these active techniques, but it can be counterproductive if used as standalone.
