### ISSUE TITLE
Error message mutate()

### ISSUE THREAD

**Issue by liiamaria** [DeAngelisA/ISSS23#9]
Hello everyone

I am struggling by understanding the following error message: 
```
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "character"
```
When I run the following code: 
`dat$YInsurance <- mutate(ifelse(test = dat$T == 1, yes = "1", no = "0"))`

Can anyone help or has had a similar issue before?
Thank you 
Lia

**Comment by liiamaria** [comment]
No worries I was able to solve it and change the code so it is working now :)

**Comment by DeAngelisA** [comment]
@liiamaria : as far as I can see the problem here is that you are mixing base R and tidyverse code. In tidyverse-R, you don't need to indicate the dataset anymore since you are (usually) piping. I show you the two code versions here below, check out careful the differences: 

```r
# Base R code:
dat$YInsurance <- ifelse(test = dat$T == 1, yes = 1, no = 0)) 

# Tidyverse code:
data <- mutate(Insurance = ifelse(test = T==1, yes = 1, no = 0))
```

**Comment by liiamaria** [comment]
Thank you very much! I will have a look at them!

**Comment by Ajdannrek** [comment]
> 
> 
> @liiamaria : as far as I can see the problem here is that you are mixing base R and tidyverse code. In tidyverse-R, you don't need to indicate the dataset anymore since you are (usually) piping. I show you the two code versions here below, check out carefully the differences:
> 
> ```r
> # Base R code:
> dat$YInsurance <- ifelse(test = dat$T == 1, yes = 1, no = 0)) 
> 
> # Tidyverse code:
> data <- mutate(Insurance = ifelse(test = T==1, yes = 1, no = 0))
> ```

@DeAngelisA : When I try the second one I still get an error message:
![R](https://user-images.githubusercontent.com/91935506/141097771-7cdc30db-59e6-41c3-85b3-105d7d5bc5fb.PNG)

**Comment by DeAngelisA** [comment]
@Ajdannrek: try adding `dat %>%` before the mutate() call.
